name: "Craig Smith"
markdown: kramdown
repository: "craigiansmith/craigiansmith.github.io"
title: "Craig's Tech Blog"
description: "Blog posts about computer science technology and software development"
gems:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyl-sitemap
  - jemoji


